[package]
name = "nathanprice-site"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
pulldown-cmark = "0.10"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
tera = "1"
walkdir = "2"
